### ISSUE TITLE
Parser.removeComments doesn't appear to work

### ISSUE THREAD

**Issue by mschwerhoff** [dzufferey/scala-smtlib-interface#2]
It seems that `Parser.removeComments` doesn't actually remove comments, as illustrated by the following Scala scripts:

```
import dzufferey.smtlib.Parser

val str = """
(forall ((r $Ref)) (! ; r@222
  true
  ; :pattern ((down r))
  ; :qid |name|
))
"""

val strWithoutComments = Parser.removeComments(str)

assert(str == strWithoutComments) /* Succeeds, but should not */
```

**Comment by dzufferey** [comment]
@mschwerhoff It seems the issue is that unix, windows, and old macs have different EOL characters. I pushed a version that should support the three platforms. Unfortunately, I only have linux machines around. Can you test the current version on your machine and let me know if that works?
Thanks

**Comment by mschwerhoff** [comment]
Thanks for the quick fix! On my Windows machine, comments are now removed when using either Windows' and Unix' EOL characters.

**Comment by mschwerhoff** [comment]
Thanks for the quick fix! On my Windows machine, comments are now removed when using either Windows' and Unix' EOL characters.
